version: '3.7'

services:
    node-app:
        image: node:14-alpine
        environment:
            API_BACKEND_BASE_URL: "http://help-to-grow-backend_node-app_1:3000"
            NODE_ENV: "development"
            SESSION_MONGODB_URL: mongodb://mongodb:27017/sessions
            SESSION_KEY: some_secure_key_goes_here
            SESSION_USE_SECURE_COOKIES: "false"
        ports:
            - 3001:3000
        working_dir: /opt/app
        volumes:
            - ./:/opt/app:ro
        command: npm run start:dev
        networks:
            - web
            - internal

    mongodb:
        image: mongo:3.6.23
        ports:
            - 4000:27017
        networks:
            - internal

networks:
    web:
        external: true
    internal:
        external: true
        name: help_to_grow_internal_network